Import('env library')

env = env.Clone(need_libpng=1,need_libjpeg=1,need_openexr=1,need_openmesh=1,need_gmp=1)

# Minimal dependencies:
# env = env.Clone(need_libpng=0,need_libjpeg=0,need_openexr=0,need_openmesh=0,need_python=0)

library(env,'geode',pyname='geode_wrap')
