#!/usr/bin/env python

from __future__ import division,print_function
from numpy import *

# Octahedron mesh
X = tuple(tuple((-1)**j*(arange(3)==i)) for i in (0,1,2) for j in (0,1))
tris = []
for x in -1,1:
  for y in -1,1:
    for z in -1,1:
      a = asarray(((x,0,0),(0,y,0),(0,0,z)))
      i = [X.index(tuple(b)) for b in a]
      if dot(cross(a[1]-a[0],a[2]-a[0]),(x,y,z)) > 0:
        tris.append(i)
      else:
        tris.append(i[::-1])
print('static const IV tris[] = {%s};'%','.join('IV(%d,%d,%d)'%(i,j,k) for i,j,k in tris))
print('static const TV X[] = {%s};'%','.join('TV(%d,%d,%d)'%(x,y,z) for x,y,z in X))
