// Various groups

#include <other/core/vector/group.h>
#include <other/core/vector/Rotation.h>
namespace other {

typedef real T;
typedef Vector<T,3> TV;

const T s = sqrt(.5);
#define Q Rotation<TV>::from_components

// Generated by group-helper: DO NOT EDIT
const Rotation<TV> octahedral_group[24] = {Q(1,0,0,0),Q(0,1,0,0),Q(s,s,0,0),Q(s,-s,0,0),Q(0,0,1,0),Q(0,0,0,1),Q(0,0,s,s),Q(0,0,-s,s),Q(0,s,s,0),Q(s,0,0,s),Q(.5,.5,.5,.5),Q(.5,-.5,-.5,.5),Q(s,0,0,-s),Q(0,-s,s,0),Q(-.5,-.5,.5,.5),Q(-.5,.5,-.5,.5),Q(-.5,.5,.5,.5),Q(.5,.5,-.5,.5),Q(s,0,-s,0),Q(0,s,0,s),Q(-.5,-.5,-.5,.5),Q(.5,-.5,.5,.5),Q(s,0,s,0),Q(0,-s,0,s)};

}
