//#####################################################################
// Class Vector
//#####################################################################
#include <other/core/vector/convert.h>

namespace other {

OTHER_DEFINE_VECTOR_CONVERSIONS(OTHER_CORE_EXPORT,2,int)
OTHER_DEFINE_VECTOR_CONVERSIONS(OTHER_CORE_EXPORT,3,int)
OTHER_DEFINE_VECTOR_CONVERSIONS(OTHER_CORE_EXPORT,4,int)
OTHER_DEFINE_VECTOR_CONVERSIONS(OTHER_CORE_EXPORT,2,short int)
OTHER_DEFINE_VECTOR_CONVERSIONS(OTHER_CORE_EXPORT,3,short int)
OTHER_DEFINE_VECTOR_CONVERSIONS(OTHER_CORE_EXPORT,4,short int)
OTHER_DEFINE_VECTOR_CONVERSIONS(OTHER_CORE_EXPORT,1,real)
OTHER_DEFINE_VECTOR_CONVERSIONS(OTHER_CORE_EXPORT,2,real)
OTHER_DEFINE_VECTOR_CONVERSIONS(OTHER_CORE_EXPORT,3,real)
OTHER_DEFINE_VECTOR_CONVERSIONS(OTHER_CORE_EXPORT,4,real)

}
