// Exact geometric predicates
#pragma once

#include <other/core/vector/Vector.h>
#include <other/core/exact/predicates-generated.h> // Pull in autogenerated predicates
namespace other {

// Add trivial predicates as inline functions.  Note that infinitesimals come in decreasing order.

// Is b.x > a.x?
static inline bool rightwards(const int ai, const Vector<exact::Quantized,2> a, const int bi, const Vector<exact::Quantized,2> b) {
  return b.x>a.x || (b.x==a.x && ai>bi);
}

// Is b.y > a.y?
static inline bool upwards(const int ai, const Vector<exact::Quantized,2> a, const int bi, const Vector<exact::Quantized,2> b) {
  return b.y>a.y || (b.y==a.y && ai>bi);
}

// Is a[i] < b[i]?
template<int d> static inline bool axis_less(const int axis, const int ai, const Vector<exact::Quantized,d> a, const int bi, const Vector<exact::Quantized,d> b) {
  return b[axis]>a[axis] || (b[axis]==a[axis] && ai>bi);
}

}
