//#####################################################################
// Class Vector
//#####################################################################
#include <geode/vector/convert.h>

namespace geode {

GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,2,int)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,3,int)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,4,int)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,2,short int)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,3,short int)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,4,short int)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,1,real)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,2,real)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,3,real)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,4,real)

}
