//#####################################################################
// Class Vector
//#####################################################################
#include <geode/vector/convert.h>

namespace geode {

GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,2,int)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,3,int)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,4,int)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,2,short int)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,3,short int)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,4,short int)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,1,float)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,2,float)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,3,float)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,4,float)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,1,double)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,2,double)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,3,double)
GEODE_DEFINE_VECTOR_CONVERSIONS(GEODE_CORE_EXPORT,4,double)

}
